### ISSUE TITLE
Implement WebAnnotation to enable quoting 

### ISSUE THREAD

**Issue by jibe-b** [dis-moi/extension#712]
An example is https://web.hypothes.is/#features. They provide a webextension to annotate texts and have the annotations shown with an highlight of the text when a user visits the page.

This would enable a contribution made through the dismoi extension to be linked to a selection of text.

(Note that the webannotation protocol consists in storing the 100 characters before and after the selected text to enable a matching with a text, even with a minimum of variation on the page. An option would even be to couple it with web.archive.org to keep track of the history of a page)

**Comment by MaartenLMEM** [comment]
Hi @jibe-b 
Thanks for sharing this. I wrote an analysis of this feature value here : https://github.com/dis-moi/extension/wiki/Int%C3%A9r%C3%AAt-de-l%E2%80%99annotation-de-texte-pour-DisMoi-:-comparaison-avec-Genius-et-Hypothes.is 
Also : 
- A question behind this issue is of course : Why should we developp this feature ? 
- It's important to  distinguish between text annotation feature and recognising some words in a page (matching context). In this case, you can add an texte annotation, but also a page annotation. 
- I have to move our product Kanban board on Github so that everyone can see what's going on and what's planned.

**Comment by lutangar** [comment]
@MaartenLMEM do we agree that this feature won't be part of __DisMois__ per your analysis?.
> Thanks for sharing this. I wrote an analysis of this feature value here : https://github.com/dis-moi/extension/wiki/Int%C3%A9r%C3%AAt-de-l%E2%80%99annotation-de-texte-pour-DisMoi-:-comparaison-avec-Genius-et-Hypothes.is

**Comment by MaartenLMEM** [comment]
@lutangar Yes, at least  not this year. And later probably not.

**Comment by lutangar** [comment]
Alright, closing this then. Feel free to reopen it when relevant.
