### ISSUE TITLE
Afficher sur la page profil de chaque éclaireur les bulles qu’il a relayée  

### ISSUE THREAD

**Issue by KaliviArf** [dis-moi/extension#819]
Peut-on faire en sorte que sur chaque profil d'éclaireur, soit relayé les bulles qu'il a relayé. 

Priorité sur l'éclaireur "Circuits courts Aquitaine" (besoin en com) 
En effet, Circuits courts Aquitaine n’a aujourd’hui qu’un seule bulle, il en aurait des dizaines sur son profil si ses relais de bulles étaient affichées ...

De plus, de manière générale, cette action permettra de convaincre plus facilement un utilisateur de s’abonner à tel ou tel éclaireur...

Dans une seconde mesure, cela permettrait  aussi à un journaliste local de parler de ces profils locaux ;)
Merci !
@christpet 
![image](https://user-images.githubusercontent.com/78505335/110120654-9e1e2a00-7dbd-11eb-83e8-44950bb697a1.png)

**Comment by KaliviArf** [comment]
@christpet

**Comment by christpet** [comment]
Thank you for this, @KaliviArf, great idea! The next step is to figure out how to display this. Are we thinking of doing it similarly to twitter retweets?
![image](https://user-images.githubusercontent.com/32476396/111357263-72d2ef00-8689-11eb-9565-fd60c29df607.png)

We can just put a retweet symbol and a bit of text on the top saying "relaye".

I'm going to wait a bit to put this in front of the dev team because it's not top priority, but I will leave it in the backlog for folks to estimate when they have a moment.

Next step: What size would this feature implementation be? XS - S - M - L - XL

**Comment by MaartenLMEM** [comment]
pris en charge par https://github.com/dis-moi/extension/issues/772
