### ISSUE TITLE
New onboarding

### ISSUE THREAD

**Issue by newick** [dis-moi/extension#837]
**Describe the feature/improvement**
To help new Users to discover the extension.

**Target user**
new Users.

**User stories**
As a new User, after installing the extension from a store it opens the onboarding page.
If I come from Chrome, I have a screen explaining how to pin the extension to my browser bar. The screen is useless on Firefox.
Then I can visit the pre-chosen éclaireurs to select new, remove the one I don't want.

**Technical implementation notes**
So far I did a POC in a [repo](https://github.com/dis-moi/onboarding-poc). 
The idea is to embed the code in the extension one to use the existing styles and adds code for interaction.

I'll need help for:

![image](https://user-images.githubusercontent.com/657454/111165882-d2ed6680-859f-11eb-935c-da7c0f3f7012.png)
- detecting that the pinning video ended 
- replaying it with the left button
- going to the next screen with an explanation about the chosen éclaireurs and éclaireuses (design in progress)
- linking to the /eclaireurs' page with the "suivis" tab chosen

**Additional context**
Here is @coffeeandpixel [design](https://xd.adobe.com/view/21488c5a-d91e-4913-a9bc-06b63f58ba73-741b/)

**Comment by christpet** [comment]
@gregoirelacoste here is an important project where we need your help. Are you up for it? :)

@newick is working on integrating this animation & video, but he needs some help with the functionality. You can see what he needs help with above.

Feel free to ping Erick or me with questions!

**Comment by gregoirelacoste** [comment]
@christpet thx for the brief, I start working on it right now

**Comment by gregoirelacoste** [comment]
@lutangar @JalilArfaoui I suggest to create an folder OnBoarding inside components>organisms and begin to work with storybook. 
I will dispatch the new atoms in the right folders later, ok for you ?

**Comment by lutangar** [comment]
Do as you see fit. As long as the components end up in the right folder, fine by me.

**Comment by gregoirelacoste** [comment]
@newick all is done but for the moment we can't see the video on storybook. Storybook do not handle assets for now. You can see the result on profiles : http://localhost:8080/eclaireurs?pk_campaign=installed
I just create new issue and will fix it in few moment  #865 cc @christpet  @lutangar

**Comment by MaartenLMEM** [comment]
Hi guys,
I remember today onboarding feature intended to new users will have **impact on users that had already installed extension**.  And it will affect a lot fo them.
**What 's the problem?**
For an unknown reasons (see belox), their extension, already installed, opens onboarding page.  
So as user, you receive a message : "hey you just have installed Dismoi, thank you !". This is very unsafe for users : DisMoi installs itself like a virus !
At best it s experienced as an annoying event, in many case it generates uninstallations. A part of them take time to tell us on unstallation form : _"L'extension s'est réinstallée toute seule sans que je ne le demande." 

Currently, onboarding page is list of contributors. Yet, it s much less frightening than an confirmed installation message.

**Events that cause this unexpected onboarding for old users**
I do not know precisely what happens. But I have identified one situation : 
User launch a chrome (or firefox) session on another computer. (I experienced it a long time ago on a computer I did not use since a long time)

**What can we do ?**
1. First, look out with current feature on words ans images we diplay on installation confirmation page. 
For example, for those old users, it s better to say "DisMoi est en cours de paramétrage, veuillez patienter" than "DisMoi est en cours d'installation". 
2. Make a quick investigatation about 'nstallation and activation events in Chrome and Firefox add-ons. If it s not easy to know and understand, create a special issue that investigate if it is possible to separate new installation experience and this kind of reativation experience. 
3. Complete this feature which we are waiting since months( (!) : Knowing what is the id of users who uninstall their add-on. [See here in trello](https://trello.com/c/qE6e4Vpi/587-desinstallation-ajouter-lid-de-lextension-dans-le-formulaire-afin-de-pourvoir-recouper-avec-les-stats)

**Comment by gregoirelacoste** [comment]
hi @MaartenLMEM new onBoarding (I don't know how the old one worked) is only activated when user is on this specific URL : eclaireurs?pk_campaign=**installed**
The user is redirected on this URL after he install the app.
So if i understand you mean that is there other cases which fire this redirection to this specific URL ?

**Comment by MaartenLMEM** [comment]
> you mean that is there other cases which fire this redirection to this specific URL ?
Yes. And I know one origin of these cases (which i describe upper), but there are probably more if we look at desinstallation reasons shared by users cc @christpet .

**Comment by lutangar** [comment]
Just to support @MaartenLMEM concerns in https://github.com/dis-moi/extension/issues/837#issuecomment-808754823
This will happens, and people will complains... just saw @gregoirelacoste opened #882 to track this down, so this is fine, I'll add more info there.

**Comment by MaartenLMEM** [comment]
Thanks @lutangar  Clearly, from my experience, if current feature is pushed in production in the state I saw it (wording, images...), we will probably have an increase of uninstallations.

**Comment by MaartenLMEM** [comment]
On hold, some design rework needed

**Comment by gregoirelacoste** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Retour newOnboarding](https://trello.com/c/75dRkhPB/423-retour-newonboarding)

**Comment by MaartenLMEM** [comment]
design review made with @newick this morning
some changes planned for this week on wording and on loading labels
