### ISSUE TITLE
Minimal posthog setup

### ISSUE THREAD

**Issue by lutangar** [dis-moi/extension#967]

**Comment by MaartenLMEM** [comment]
@zhinu is it ok on your side ? "Minimum" is working ? 
Can you just add some notes about this minimum and forecast next steps ?

**Comment by zhinu** [comment]
Basically :
- Posthog implementation so far is working ( POC [X] )

Next steps :
[] - Verify the accuracy of the various data (this week)
[] - Solve the issue related to the limit of authorized events (next week)
[] - Add other analytical functions (next week)
[] - Implement for website v2 (incl. AB testing & heatmap) (later)

**Comment by zhinu** [comment]
Features that seem to be missing in Posthog :
- Cohorts can't be timed based (see issue https://github.com/PostHog/posthog/issues/199 )
       - i.e. users that have logged in for the first time one month ago
       - i.e. users that haven't logged in in the past 7 days
- No new install was found in proding (maybe bad request from me)

Questions we need an answer to :
- how does a certain group behaves (those subscribed to a certain contributor for instance)?
- What was the experience of users that used the app once and never came back?

Implementation improvement :
- Instead of having notices id, we should have also notices name, contributor and relay.
- API driven extraction of data to dashboard
